//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustGestures.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JustGestures.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap about {
            get {
                object obj = ResourceManager.GetObject("about", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon about1 {
            get {
                object obj = ResourceManager.GetObject("about1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap activate {
            get {
                object obj = ResourceManager.GetObject("activate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon add_app16 {
            get {
                object obj = ResourceManager.GetObject("add_app16", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap add_application {
            get {
                object obj = ResourceManager.GetObject("add_application", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap add_gesture {
            get {
                object obj = ResourceManager.GetObject("add_gesture", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon add_gesture16 {
            get {
                object obj = ResourceManager.GetObject("add_gesture16", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon alert {
            get {
                object obj = ResourceManager.GetObject("alert", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap application {
            get {
                object obj = ResourceManager.GetObject("application", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap auto_off {
            get {
                object obj = ResourceManager.GetObject("auto_off", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap auto_on {
            get {
                object obj = ResourceManager.GetObject("auto_on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon autobehave {
            get {
                object obj = ResourceManager.GetObject("autobehave", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap base_mouse {
            get {
                object obj = ResourceManager.GetObject("base_mouse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap browser_home {
            get {
                object obj = ResourceManager.GetObject("browser_home", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap browser_next {
            get {
                object obj = ResourceManager.GetObject("browser_next", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap browser_prev {
            get {
                object obj = ResourceManager.GetObject("browser_prev", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap browser_refresh {
            get {
                object obj = ResourceManager.GetObject("browser_refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap browser_stop {
            get {
                object obj = ResourceManager.GetObject("browser_stop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btn_left_modifier {
            get {
                object obj = ResourceManager.GetObject("btn_left_modifier", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btn_left_trigger {
            get {
                object obj = ResourceManager.GetObject("btn_left_trigger", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btn_middle_modifier {
            get {
                object obj = ResourceManager.GetObject("btn_middle_modifier", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btn_middle_trigger {
            get {
                object obj = ResourceManager.GetObject("btn_middle_trigger", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btn_right_modifier {
            get {
                object obj = ResourceManager.GetObject("btn_right_modifier", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btn_right_trigger {
            get {
                object obj = ResourceManager.GetObject("btn_right_trigger", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btn_wheel_down {
            get {
                object obj = ResourceManager.GetObject("btn_wheel_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btn_wheel_up {
            get {
                object obj = ResourceManager.GetObject("btn_wheel_up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btn_x1_modifier {
            get {
                object obj = ResourceManager.GetObject("btn_x1_modifier", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btn_x1_trigger {
            get {
                object obj = ResourceManager.GetObject("btn_x1_trigger", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btn_x2_modifier {
            get {
                object obj = ResourceManager.GetObject("btn_x2_modifier", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btn_x2_trigger {
            get {
                object obj = ResourceManager.GetObject("btn_x2_trigger", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon clock {
            get {
                object obj = ResourceManager.GetObject("clock", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap close_hover {
            get {
                object obj = ResourceManager.GetObject("close_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap close_normal {
            get {
                object obj = ResourceManager.GetObject("close_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap close_pushed {
            get {
                object obj = ResourceManager.GetObject("close_pushed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap deactivate {
            get {
                object obj = ResourceManager.GetObject("deactivate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap delete {
            get {
                object obj = ResourceManager.GetObject("delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap designedBack2 {
            get {
                object obj = ResourceManager.GetObject("designedBack2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap desktop {
            get {
                object obj = ResourceManager.GetObject("desktop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap disable {
            get {
                object obj = ResourceManager.GetObject("disable", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon download_ico {
            get {
                object obj = ResourceManager.GetObject("download_ico", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap edit_copy {
            get {
                object obj = ResourceManager.GetObject("edit_copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap edit_cut {
            get {
                object obj = ResourceManager.GetObject("edit_cut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap edit_paste {
            get {
                object obj = ResourceManager.GetObject("edit_paste", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap enable {
            get {
                object obj = ResourceManager.GetObject("enable", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap favourites {
            get {
                object obj = ResourceManager.GetObject("favourites", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flattr_badge_large {
            get {
                object obj = ResourceManager.GetObject("flattr_badge_large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap folder_open {
            get {
                object obj = ResourceManager.GetObject("folder_open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap internet {
            get {
                object obj = ResourceManager.GetObject("internet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon just_gestures {
            get {
                object obj = ResourceManager.GetObject("just_gestures", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap keystrokes {
            get {
                object obj = ResourceManager.GetObject("keystrokes", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lock2 {
            get {
                object obj = ResourceManager.GetObject("lock2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap logo128x128_opacity {
            get {
                object obj = ResourceManager.GetObject("logo128x128_opacity", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon logo16x16 {
            get {
                object obj = ResourceManager.GetObject("logo16x16", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap logo32 {
            get {
                object obj = ResourceManager.GetObject("logo32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon logo48x48 {
            get {
                object obj = ResourceManager.GetObject("logo48x48", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap logoff {
            get {
                object obj = ResourceManager.GetObject("logoff", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mail {
            get {
                object obj = ResourceManager.GetObject("mail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap main_form {
            get {
                object obj = ResourceManager.GetObject("main_form", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap media {
            get {
                object obj = ResourceManager.GetObject("media", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap media_pause {
            get {
                object obj = ResourceManager.GetObject("media_pause", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap media_play {
            get {
                object obj = ResourceManager.GetObject("media_play", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap media_skip_back {
            get {
                object obj = ResourceManager.GetObject("media_skip_back", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap media_skip_forward {
            get {
                object obj = ResourceManager.GetObject("media_skip_forward", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap media_stop {
            get {
                object obj = ResourceManager.GetObject("media_stop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap minimize_hover {
            get {
                object obj = ResourceManager.GetObject("minimize_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap minimize_normal {
            get {
                object obj = ResourceManager.GetObject("minimize_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap minimize_pushed {
            get {
                object obj = ResourceManager.GetObject("minimize_pushed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap modify {
            get {
                object obj = ResourceManager.GetObject("modify", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon modify16 {
            get {
                object obj = ResourceManager.GetObject("modify16", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon my_cursor_image {
            get {
                object obj = ResourceManager.GetObject("my_cursor_image", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap options {
            get {
                object obj = ResourceManager.GetObject("options", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon options16 {
            get {
                object obj = ResourceManager.GetObject("options16", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Paypal_DonateButton {
            get {
                object obj = ResourceManager.GetObject("Paypal_DonateButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap restart {
            get {
                object obj = ResourceManager.GetObject("restart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] RotatingCross {
            get {
                object obj = ResourceManager.GetObject("RotatingCross", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap shell {
            get {
                object obj = ResourceManager.GetObject("shell", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap shutdown {
            get {
                object obj = ResourceManager.GetObject("shutdown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sleep {
            get {
                object obj = ResourceManager.GetObject("sleep", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap start_hover {
            get {
                object obj = ResourceManager.GetObject("start_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap start_normal {
            get {
                object obj = ResourceManager.GetObject("start_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap start_pushed {
            get {
                object obj = ResourceManager.GetObject("start_pushed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap system_desktop20 {
            get {
                object obj = ResourceManager.GetObject("system_desktop20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap system_desktop24 {
            get {
                object obj = ResourceManager.GetObject("system_desktop24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap system_desktop32 {
            get {
                object obj = ResourceManager.GetObject("system_desktop32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap system_global20 {
            get {
                object obj = ResourceManager.GetObject("system_global20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap system_global24 {
            get {
                object obj = ResourceManager.GetObject("system_global24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap system_global32 {
            get {
                object obj = ResourceManager.GetObject("system_global32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap system_taskbar20 {
            get {
                object obj = ResourceManager.GetObject("system_taskbar20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap system_taskbar24 {
            get {
                object obj = ResourceManager.GetObject("system_taskbar24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap system_taskbar32 {
            get {
                object obj = ResourceManager.GetObject("system_taskbar32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tab_add {
            get {
                object obj = ResourceManager.GetObject("tab_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tab_close {
            get {
                object obj = ResourceManager.GetObject("tab_close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tab_switcher {
            get {
                object obj = ResourceManager.GetObject("tab_switcher", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tab_undo {
            get {
                object obj = ResourceManager.GetObject("tab_undo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap text {
            get {
                object obj = ResourceManager.GetObject("text", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap turnoff {
            get {
                object obj = ResourceManager.GetObject("turnoff", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap unreadable20 {
            get {
                object obj = ResourceManager.GetObject("unreadable20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap unreadable24 {
            get {
                object obj = ResourceManager.GetObject("unreadable24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap unreadable32 {
            get {
                object obj = ResourceManager.GetObject("unreadable32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap view_actions {
            get {
                object obj = ResourceManager.GetObject("view_actions", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap view_gestures {
            get {
                object obj = ResourceManager.GetObject("view_gestures", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap volume_control {
            get {
                object obj = ResourceManager.GetObject("volume_control", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap volume_control2 {
            get {
                object obj = ResourceManager.GetObject("volume_control2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap volume_down {
            get {
                object obj = ResourceManager.GetObject("volume_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap volume_mute {
            get {
                object obj = ResourceManager.GetObject("volume_mute", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap volume_up {
            get {
                object obj = ResourceManager.GetObject("volume_up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap web_search20 {
            get {
                object obj = ResourceManager.GetObject("web_search20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap web_search32 {
            get {
                object obj = ResourceManager.GetObject("web_search32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap window {
            get {
                object obj = ResourceManager.GetObject("window", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap window_close {
            get {
                object obj = ResourceManager.GetObject("window_close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap window_fullscreen {
            get {
                object obj = ResourceManager.GetObject("window_fullscreen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap window_max {
            get {
                object obj = ResourceManager.GetObject("window_max", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap window_min {
            get {
                object obj = ResourceManager.GetObject("window_min", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap window_side_by_side {
            get {
                object obj = ResourceManager.GetObject("window_side_by_side", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap window_switcher {
            get {
                object obj = ResourceManager.GetObject("window_switcher", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap window_topmost {
            get {
                object obj = ResourceManager.GetObject("window_topmost", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap window_transparent {
            get {
                object obj = ResourceManager.GetObject("window_transparent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap window_vertical {
            get {
                object obj = ResourceManager.GetObject("window_vertical", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon wizard {
            get {
                object obj = ResourceManager.GetObject("wizard", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap zoom {
            get {
                object obj = ResourceManager.GetObject("zoom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap zoom_in {
            get {
                object obj = ResourceManager.GetObject("zoom_in", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap zoom_out {
            get {
                object obj = ResourceManager.GetObject("zoom_out", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
